- id: pytest-changed
  name: pytest-changed
  description: Run pytest for tests related to staged Python files in pre-commit.
  entry: pytest-changed
  language: python
  types_or: [python]
  pass_filenames: true
  always_run: false
